export class Inventario { 
    constructor(
        public tipo?: string,
        public asignado?: string,
        public modelo?: string,
        public marca?: string,
        public descripcion?: string,
        public serie?: string,
        public sistemaoperativo?: string,
        public cargador?: string,
        public teclado?: string,
        public mouse?: string,
        public monitor?: string,
        public email?: string,
        public numerotelefonico?: string,
        public auriculares?: string,
        public control?: string,
        public referencia?: string, 
        public marcateclado?: string,
        public referenciateclado?: string,
        public numeroserieteclado?: string,
        public marcamouse?: string,
        public referenciamouse?: string,
        public numeroseriemouse?: string,
        public marcamonitor?: string,
        public referenciamonitor?: string,
        public numeroseriemonitor?: string,
        public ram?: string,
        public discoduro?: string,
        public nombredeldispositivo?: string,
        public ranurasdisponibles?: string,
        public procesador?: string,
        public tarjetagrafica?: string
    ) {}
}